//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, serde::Serialize, serde::Deserialize)]
#[sea_orm(table_name = "words")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub word: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub phonetic: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub definition: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub translation: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub pos: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub collins: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub oxford: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub tag: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub bnc: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub frq: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub exchange: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub detail: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub audio: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
