name: Release

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo check
      - run: cargo test
      - run: rustup toolchain list
      - name: Install toolchains
        run: |
          rustup target add x86_64-pc-windows-gnu
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin
          apt install -y build-essential
      - name: Build release
        run: |
          cargo build --release
          cargo build --release --target x86_64-pc-windows-gnu
          cargo build --release --target x86_64-apple-darwin
          cargo build --release --target aarch64-apple-darwin
      - name: Rename releases
        run: |
          mkdir release
          mv target/release/runslate release/runslate-x86_64-unknown-linux-gnu
          mv target/x86_64-pc-windows-gnu/release/runslate.exe release/runslate-x86_64-pc-windows-gnu.exe
          mv target/x86_64-apple-darwin/release/runslate release/runslate-x86_64-apple-darwin
          mv target/aarch64-apple-darwin/release/runslate release/runslate-aarch64-apple-darwin
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cross arch releases
          path: release
      - name: Download artifacts
        uses: actions/download-artifact@v3
